<?php
if(isset($_POST['cerrar'])){
    echo"<script>alert('Ha leido los Terminos y Condiciones')</script>";
    echo "<script languaje='javascript' type='text/javascript'>window.close();</script>";
}
?>

<!DOCTYPE html>
<html lang="en">
<script> 
function centrar() { 
    iz=(screen.width-document.body.clientWidth) / 2; 
    de=(screen.height-document.body.clientHeight) / 2; 
    moveTo(iz,de); 
}     
</script>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../../lib/animate/animate.min.css" rel="stylesheet">
    <link href="../../lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body onload="centrar();">
<table class="table">
    <p align="center"><b>CONDICIONES GENERALES DE USO DEL PORTAL EXPERTOBRA</b></p>
    <p class="text-md-start">

        <b>PREÁMBULO</b><br><br>
        <b>EXPERTOBRA S.A.S BIC (en adelante “EXPERTOBRA”)</b> ofrece a los usuarios de internet el Sitio Web www.expertobra.com de forma gratuita, reservando algunos servicios específicos al pago de una suscripción, pago puntual de mentorías para candidatos o cursos.
        EXPERTOBRA entiende por “Usuario Particular” u “Oferente de Trabajo” o “Candidato” aquellas personas físicas que acceden al Sitio Web de EXPERTOBRA para buscar consultoría en áreas de Ingeniería Civil, Arquitectura, Topografía, Inmuebles, Cursos Online, Cursos Presenciales, empleo o recibir servicios relacionados.
        EXPERTOBRA entiende por “Usuario Profesional” o “Demandante de Empleo” o 'Empresa', aquellas empresas o reclutadores que utilicen los servicios de EXPERTOBRA y accedan al Sitio Web del que este último es titular.
        El Usuario Particular y el Usuario Profesional serán referidos conjuntamente, cuando así proceda, como “Usuario” o “Usuarios”.
        Todo Usuario acepta, desde el mismo momento en el que accede, sin ningún tipo de reserva, el contenido de las presentes Condiciones Legales, la “Política de Privacidad y Cookies”, así como, en su caso, las Condiciones Particulares que puedan complementar, sustituir o modificar las referidas condiciones en relación con los servicios y contenidos del Portal Web acordadas, en su caso, en la correspondiente Orden de Servicio, Contrato o Condiciones de Servicio específicas (en adelante, referidas conjuntamente como las “Condiciones Legales”). El Usuario deberá leer detenidamente las Condiciones Legales antes del uso y/o contratación de cualquier servicio del Portal Web bajo su entera responsabilidad Condiciones Legales). El Usuario deberá leer detenidamente las Condiciones Legales antes del uso y/o contratación de cualquier servicio del Portal Web bajo su entera responsabilidad.
        Para acceder a nuestro portal web el Usuario debe tener 18 años de edad o más. Si el Usuario es menor de 18 años o menor a la mayoría legal de su país, su uso de nuestro Portal Web y asunción de cualquier obligación debe estar bajo la supervisión de sus padres o tutor u otro adulto responsable. En caso de acceder al Portal Web o utilizarlo en calidad de empleado o representante de un Usuario Profesional, se considera que éste declara y garantiza que tienes la autoridad para vincular al Usuario Profesional a las presentes Condiciones Legales.
        Con carácter general el acceso al Portal Web no exige registro de los Usuarios en opciones como consultorías, inmuebles, o cursos online y presenciales. No obstante, EXPERTOBRA condiciona la utilización de los servicios al registro del Usuario y previa suscripción anual. El tratamiento de los datos personales que se incluyan será conforme a nuestra Política de Privacidad.
        <br><br>
         
        
        El Usuario puede acceder, imprimir, descargar y guardar las Condiciones Legales, las cuales están permanentemente accesibles en el Sitio Web a través del enlace “Términos y Condiciones”.
        EXPERTOBRA S.A.S BIC, podrá modificar sin previo aviso el contenido de las Condiciones Legales. Por ello recomienda al Usuario leerlas cada vez que acceda al Portal Web. Asimismo, EXPERTOBRA S.A.S BIC, podrá modificar sin previo aviso el diseño, presentación y/o configuración de este Sitio Web, así como algunos o todos los servicios ofrecidos, y añadir servicios nuevos.
        En cualquier caso, <b>EXPERTOBRA S.A.S BIC</b> se reserva el derecho de denegar el acceso a este Sitio Web, en cualquier momento y sin necesidad de previo aviso, a aquellos Usuarios que incumplan cualesquiera de las Condiciones Legales que les sean de aplicación.
        <br><br>
        <b>OBJETO</b><br><br>
        
        La finalidad de este Portal Web es la de poner en contacto a Oferentes de Servicios para el Sector Construcción, ofreciendo principalmente los siguientes servicios: Consultorías en áreas de Ingeniería Civil, Arquitectura, Topografía, Inmuebles, Cursos Online, Cursos Presenciales, empleo o recibir servicios relacionados.
        La publicación de Consultorías y la posibilidad de obtener un contacto directo con especialistas en cada una de ellas es gratuita, y se comunicaran a través del botón de WhatsApp con el numero registrado por la empresa EXPERTOBRA, para posteriormente ser atendidas por el especialista o experto en dichas Consultorías 
        La publicación de Inmuebles y la posibilidad de obtener un contacto directo con los asesores comerciales encargados de su venta, en cada una de ellas es gratuita, y se comunicaran a través del botón de WhatsApp con el numero registrado por la empresa EXPERTOBRA, para posteriormente ser atendidas por el Asesor Comercial de su Empresa correspondiente.
        La búsqueda de empleo a través del Portal Web EXPERTOBRA es gratuita para los candidatos. Sin embargo, la inscripción y aplicación en las ofertas de empleo publicadas por las empresas es por suscripción de 12 meses. Además, el portal web ofrece otros servicios de pago de valor añadido para los Candidatos como lo son Mentorías para sus hojas de vida, Entrevistas de trabajo, y Pruebas psicotécnicas.
        La Inscripción en Cursos Online o Cursos Presenciales es realizada a través del pago de cada curso ofrecido en el sitio web de EXPERTOBRA. Los cursos online, son realizados por un experto en el tema contratado por EXPERTOBRA S.A.S. BIC, y se realizan en vivo a través de una plataforma externa para videollamadas llamada Microsoft Teams. Sin embargo, los cursos presenciales, son realizados por Empresas aliadas de EXPERTOBRA, y será responsabilidad de ellas, dictaminar el lugar o sede donde realizaran cada curso ofrecido.
        <br><br>
        
        <b>TERMINOS Y CONDICIONES SERVICIOS OFRECIDOS POR EXPERTOBRA</b><br><br>
        
        <b>1.	SERVICIOS DE CONSULTORIA DE INGENIERIA CIVIL, ARQUITECTURA, TOPOGRAFIA.</b><br><br>
        
        •	Responsabilidades del Usuario. El usuario se compromete a proporcionar información veraz, completa y actualizada en el momento de solicitar el servicio de consultoría y a mantener dicha información actualizada durante la contratación de este servicio, el usuario también se compromete a utilizar la plataforma de manera responsable y a cumplir con las leyes y normativas aplicables.
        <br>
        •	Responsabilidades de la empresa. La empresa actúa como intermediario en la contratación de terceros para prestar los servicios de consultorías ofrecidos a través de la plataforma. La empresa garantiza que buscara a los mejores expertos para la realización de los servicios de consultoría, pero no se hace responsable de los servicios prestados por terceros de ningún daño o perjuicio causado por dichos servicios.
        <br>
        •	Limitaciones del servicio. La empresa EXPERTOBRA S.A.S. no se hace responsable de cualquier daño o perjuicio causado por el uso de la plataforma o de los servicios prestados por terceros.
        <br>
        •	Condiciones de pago. El usuario acepta pagar los honorarios correspondientes a los servicios solicitados a través de la plataforma, según las tarifas establecidas por la empresa. Los pagos se realizarán a través de los medios de pago disponibles en la plataforma o informados al usuario.
        <br>
        •	Cancelación y reembolso. El usuario puede cancelar los servicios solicitados a través de la plataforma en cualquier momento, siempre y cuando se cumplan las condiciones establecidas en el acuerdo entre el usuario y EXPERTOBRA S.AS. Los reembolsos estarán sujetos a las políticas de cancelación y reembolso establecidas por EXPERTOBRA S.A.S.
        <br>
        •	Políticas de cancelación y reembolso. El usuario podrá cancelar los servicios contratados de consultorías de Ingeniería Civil, Arquitectura, Topografía, en cualquier momento, Si la cancelación se realiza con un plazo de 24 horas o más antes del inicio del servicio, se reembolsará el 100% del importe pagado. Si la cancelación se realiza con menos de 24 horas de antelación, no se realizará ningún reembolso. En caso de que la empresa tenga que cancelar los servicios contratados por el usuario, se reembolsará el importe total pagado por el usuario, sin derecho a ninguna retribución monetaria o de cualquier clase por la cancelación. Si el usuario desea cambiar la fecha de prestación del servicio contratado, deberá notificarlo con al menos 24 horas de antelación. En caso contrario, no se garantiza la disponibilidad del tercero prestador del servicio. Si se realiza el cambio de fecha con al menos 24 horas de antelación, se podrá reprogramar el servicio sin coste adicional. Los reembolsos se realizarán mediante el mismo método de pago utilizado en la compra. Si el usuario ha utilizado una tarjeta de crédito, el reembolso se realizará a la misma tarjeta. El tiempo de procesamiento del reembolso dependerá de la entidad bancaria del usuario.
        <br>
        •	Propiedad intelectual. Los derechos de propiedad intelectual sobre los contenidos y servicios ofrecidos a través de la plataforma pertenecen a la empresa o a terceros. La reproducción, distribución o modificación de dichos contenidos sin autorización expresa de la empresa está prohibida.
        <br>
        •	Política de privacidad y protección de datos personales. La empresa se compromete a cumplir con la normativa vigente en materia de protección de datos personales. La empresa recopila y procesa los datos personales del usuario con el fin de prestar los servicios ofrecidos a través de la plataforma. El usuario puede ejercer sus derechos de acceso, rectificación, cancelación y oposición mediante los medios establecidos en la plataforma.
        <br>
        •	Resolución de conflictos. Cualquier conflicto que surja entre el usuario y el tercero prestador del servicio será resuelto mediante los medios establecidos en el acuerdo entre el usuario y el tercero prestador del servicio.
        <br>
        •	Modificación de los términos y condiciones. La empresa se reserva el derecho de modificar estos términos y condiciones en cualquier momento. Los cambios entrarán en vigor a partir del momento de su publicación en la plataforma y serán notificados al usuario registrado en la plataforma. El uso continuado de la plataforma después de la publicación de los cambios implicará la aceptación de los mismos por parte del usuario.
        <br>
        •	Advertencia de seguridad. La plataforma se compromete a enviar un informe a todos los usuarios registrados que, aunque se han implementado medidas de seguridad para proteger la plataforma y los datos de los usuarios, ha sido vulnerada su protección por uno o más posibles ataques cibernéticos. Se informa a los usuarios que los ataques cibernéticos son un riesgo inherente en el uso de Internet y que la plataforma no se hace responsable de los daños causados por estos ataques, pero se compromete en caso de que esto suceda, a tomar las medidas legales y tecnológicas correspondientes para proteger a los usuarios registrados en la plataforma.
        <br><br>
        
        <b>2.	INMUEBLES</b><br><br>
        
        •	Responsabilidades del Usuario. El usuario se compromete a proporcionar información veraz, completa y actualizada en el momento de solicitar el servicio de pauta publicitaria en la plataforma o en las redes sociales de la plataforma, y a mantener dicha información actualizada durante la contratación de este servicio, el usuario también se compromete a utilizar la plataforma de manera responsable y a cumplir con las leyes y normativas aplicables.
        <br>
        •	Responsabilidades de Empresa de Inmuebles. La empresa es responsable de proporcionar información precisa y veraz sobre sus proyectos de vivienda, incluyendo la ubicación, el tamaño, los precios, imágenes, las características y la disponibilidad. La plataforma no se hace responsable de la veracidad o exactitud de esta información. La empresa es responsable de garantizar la calidad y el cumplimiento de sus proyectos de vivienda. La plataforma no se hace responsable de la calidad de los proyectos ofrecidos por las empresas. La empresa debe ser propietaria de los derechos de propiedad intelectual de sus proyectos de vivienda, incluyendo las imágenes y la información relacionada. La plataforma no se hace responsable de la violación de los derechos de propiedad intelectual de terceros.
        <br>
        •	Limitaciones del servicio. La empresa EXPERTOBRA S.A.S. no se hace responsable de cualquier daño o perjuicio causado por los usuarios de la plataforma o de los servicios prestados por terceros. 
        <br>
        •	Comisiones. La empresa puede estar sujeta a pagar una comisión a la plataforma EXPERTOBRA por los clientes referidos desde la plataforma hasta la sala de venta de la empresa y que realicen la compra del inmueble. Las condiciones de esta comisión estarán acordadas entre la plataforma y la empresa propietaria del inmueble.
        <br>
        •	Cancelación del registro. La plataforma se reserva el derecho de cancelar el registro o borrar cualquier publicación de las empresas en cualquier momento, si se descubre que ha proporcionado información falsa o engañosa o si se ha violado los términos y condiciones.
        <br>
        •	Propiedad intelectual. Los derechos de propiedad intelectual sobre los contenidos de cada inmueble ofrecido a través de la plataforma pertenecen a la empresa propietaria de este inmueble. La reproducción, distribución o modificación de dichos contenidos sin autorización expresa de la empresa está prohibida.
        <br>
        •	Política de privacidad y protección de datos personales. La empresa se compromete a cumplir con la normativa vigente en materia de protección de datos personales. La empresa recopila y procesa los datos personales del usuario con el fin de prestar los servicios ofrecidos a través de la plataforma. El usuario puede ejercer sus derechos de acceso, rectificación, cancelación y oposición mediante los medios establecidos en la plataforma.
        <br>
        •	Resolución de conflictos. Cualquier conflicto que surja entre el usuario y el tercero prestador del servicio será resuelto mediante los medios establecidos en el acuerdo entre el usuario y el tercero prestador del servicio.
        <br>
        •	Modificación de los términos y condiciones. La empresa se reserva el derecho de modificar estos términos y condiciones en cualquier momento. Los cambios entrarán en vigor a partir del momento de su publicación en la plataforma y serán notificados al usuario registrado en la plataforma. El uso continuado de la plataforma después de la publicación de los cambios implicará la aceptación de los mismos por parte del usuario.
        <br>
        •	Advertencia de seguridad. La plataforma se compromete a enviar un informe a todos los usuarios registrados que, aunque se han implementado medidas de seguridad para proteger la plataforma y los datos de los usuarios, ha sido vulnerada su protección por uno o más posibles ataques cibernéticos. Se informa a los usuarios que los ataques cibernéticos son un riesgo inherente en el uso de Internet y que la plataforma no se hace responsable de los daños causados por estos ataques, pero se compromete en caso de que esto suceda, a tomar las medidas legales y tecnológicas correspondientes para proteger a los usuarios registrados en la plataforma.
        <br><br>
        <b>3.	EMPLEO</b><br><br> 
        
        •	Responsabilidades del Usuario. Las empresas contratantes se comprometen a proporcionar información veraz, completa y actualizada en el momento de solicitar el servicio de publicación de ofertas laborales en la plataforma o en las redes sociales de la plataforma, y a mantener dicha información actualizada durante la contratación de este servicio, el usuario que se registre como candidato, se compromete a proporcionar información veraz, completa y actualizada de su perfil profesional al momento de subir y enviar su hoja de vida, también se compromete a utilizar la plataforma de manera responsable y a cumplir con las leyes y normativas aplicables.
        <br>
        •	Responsabilidades de Empresa contratante. La empresa es responsable de proporcionar información precisa y veraz sobre sus ofertas de empleo, incluyendo: cargo, área, ciudad, profesión, fecha de publicación, nivel educativo, salario mínimo, salario máximo, años de experiencia, competencias, además de proporcionar datos de la empresa como lo son: nombre, celular, email, tipo de contrato, jornada laboral, funciones y logo de la empresa. El usuario es responsable de proporcionar información precisa y veraz sobre sus ofertas de empleo, incluyendo: Numero de documento de identidad, nombres y apellidos completos, numero de celular, email, profesión, descripción del perfil profesional, foto para h.v. La plataforma no se hace responsable de la veracidad o exactitud de esta información, será labor de la empresa contratante la verificación de esta información, la plataforma si se compromete a la verificación de antecedentes. La empresa es responsable de garantizar la calidad y el cumplimiento de sus procesos de selección de candidatos que aplicaran a sus ofertas de empleo solicitadas. La plataforma no se hace responsable de la calidad de estos procesos de selección realizados por las empresas. La empresa deberá entregar un informe evaluativo a la plataforma donde informaran porque rechazaron a los candidatos que se inscribieron en su oferta de empleo, este informe será en un formato proporcionado por la plataforma y empresa EXPERTOBRA S.A.S. La empresa contratante debe garantizar la confidencialidad y privacidad de los datos personales de los candidatos y no compartir esta información con terceros sin el consentimiento explícito de los candidatos. Las empresas deben utilizar la información recibida solo con fines de selección de candidatos y no para ningún otro propósito. Las empresas deben cumplir con todas las leyes y regulaciones aplicables en relación con la selección de candidatos, incluyendo las leyes de igualdad de oportunidades y discriminación. Las empresas no pueden cobrar a los candidatos por el proceso de selección o por la evaluación de sus hojas de vida. Las empresas deben garantizar que los candidatos tengan derecho a acceder a su información personal y a solicitar la eliminación de su información en cualquier momento. La plataforma no será responsable de ninguna acción u omisión de las empresas con respecto al proceso de selección de candidatos.
        <br>
        •	Registro. Los usuarios deben registrarse en la plataforma para poder adquirir la suscripción anual donde deberán realizar su pago si desean acceder a la información de la oferta de empleo de su interes. Al registrarse, deben proporcionar información precisa y actualizada sobre sus habilidades, experiencia laboral y cualquier otra información relevante. 
        <br>
        •	Pago de Suscripción Anual. Los usuarios deben pagar la tarifa anual de $ 39.999 pesos colombianos para acceder a las ofertas de empleo anunciadas en la plataforma durante el período de suscripción de 1 año. La plataforma ofrece diferentes métodos de pago que son, PayPal, tarjetas de crédito y débito, para que el usuario realice el pago. La plataforma le anunciara con anticipación al usuario la fecha de vencimiento de su suscripción para que realice posteriormente su renovación. Si experimenta problemas con el pago, comuníquese con nuestro servicio de atención al cliente lo antes posible para que podamos ayudarlo a resolver el problema.
        <br>
        •	Pago de Servicios de Mentorías. Los usuarios deberán pagar la tarifa correspondiente de $49.999 pesos colombianos para acceder a cada uno de los servicios de mentoría que deseen adquirir por un tiempo de 1 hora que durara el servicio de mentoría Online. La plataforma ofrece diferentes métodos de pago que son, PayPal, tarjetas de crédito y débito, para que el usuario realice el pago. Si experimenta problemas con el pago, comuníquese con nuestro servicio de atención al cliente lo antes posible para que podamos ayudarlo a resolver el problema.
        <br>
        •	Responsabilidad de los mentores. Los mentores se comprometen a brindar servicios de mentoría profesionales y de alta calidad, que cumplan con los estándares y requisitos de la industria. Sin embargo, la plataforma no se hace responsable de las decisiones de los usuarios basadas en la mentoría recibida.
        <br>
        •	Confidencialidad. Toda la información proporcionada por los usuarios en el contexto de los servicios de mentoría se mantendrá en estricta confidencialidad por parte del mentor. Los usuarios también se comprometen a mantener la confidencialidad de cualquier información proporcionada por el mentor o por otros usuarios en el contexto de los servicios de mentoría.
        <br>
        •	Cambio de fecha. En caso de que el usuario o la persona contratada por EXPERTOBRA S.A.S. para que realice este servicio, no pueda asistir a la mentoría programada, la plataforma ofrece la opción de cambiar la fecha y hora de la sesión de mentoría. Si el usuario acepta, se fijará una nueva fecha y hora, y se procederá con la mentoría en ese momento. Sin embargo, la cancelación debe realizarse con un plazo de 24 horas de antelación o más antes del inicio del servicio, si el usuario no lo hace en este plazo de horas, su reprogramación no se realizará y la plataforma no realizará ningún tipo de reembolso. 
        <br>
        •	Cancelación y reembolso. El usuario puede cancelar los servicios solicitados a través de la plataforma en cualquier momento, siempre y cuando se cumplan las condiciones establecidas en el acuerdo entre el usuario y EXPERTOBRA S.AS. Los reembolsos estarán sujetos a las políticas de cancelación y reembolso establecidas por EXPERTOBRA S.A.S.
        <br>
        •	Políticas de cancelación y reembolso. El usuario podrá cancelar los servicios contratados de Mentoría para acompañamiento en la realización de su hoja de vida, Mentoría para entrevistas de trabajo, Mentoría para pruebas psicotécnicas, No se reembolsará el pago de los servicios de mentoría ya adquiridos, una vez realizada y finalizada la sesión de mentoría. Si la cancelación se realiza con un plazo de 24 horas o más antes del inicio del servicio, se reembolsará el 100% del importe pagado. Si la cancelación se realiza con menos de 24 horas de antelación, o si el usuario no se presenta a la fecha y hora programada para el servicio de mentoría, no se realizará ningún tipo de reembolso. Los reembolsos se realizarán mediante el mismo método de pago utilizado en la compra. Si el usuario ha utilizado una tarjeta de crédito, el reembolso se realizará a la misma tarjeta. El tiempo de procesamiento del reembolso dependerá de la entidad bancaria del usuario. En caso de que la plataforma cierre o no pueda cumplir con los términos de suscripción acordados, nos reservamos el derecho de no ofrecer reembolsos a los usuarios por la suscripción anual ya adquirida, correspondiente al tiempo que no se podrá brindar el servicio de suscripción.
        <br>
        •	Excepciones. Si un usuario no puede asistir a una mentoría programada debido a una enfermedad o imposibilidad de asistir, se puede considerar una excepción a la política de cancelación y reembolso. En este caso, el usuario debe proporcionar un certificado médico u otra documentación que respalde su solicitud de excepción. La plataforma analizará el caso y determinará si se realizará una reprogramación de la fecha del servicio, o si realiza un reembolso total. Los reembolsos se realizarán mediante el mismo método de pago utilizado en la compra. Si el usuario ha utilizado una tarjeta de crédito, el reembolso se realizará a la misma tarjeta. El tiempo de procesamiento del reembolso dependerá de la entidad bancaria del usuario.
        <br>
        •	Veracidad de la información de usuarios. Los usuarios son responsables de proporcionar información precisa y veraz sobre su experiencia y habilidades laborales. La plataforma no se hace responsable de la veracidad o exactitud de esta información.
        <br>
        •	Publicación de ofertas. Las empresas contratantes son responsables de brindar la información de la oferta de empleo precisa y completa para que plataforma realice su publicación, incluyendo cargo, área, ciudad, profesión, fecha de publicación, nivel educativo, salario mínimo, salario máximo, años de experiencia, competencias, además de proporcionar datos de la empresa como lo son: nombre, celular, email, tipo de contrato, jornada laboral, funciones y logo de la empresa.
        <br>
        •	Modificaciones a los términos y condiciones. La plataforma puede modificar los términos y condiciones en cualquier momento y sin previo aviso. Se espera que los usuarios cumplan con los nuevos términos y condiciones al continuar utilizando la plataforma.
        <br>
        •	Cancelación del registro. La plataforma se reserva el derecho de cancelar el registro de los usuarios o de las empresas contratantes si se descubre que han proporcionado información falsa o engañosa. Nos reservamos el derecho de rechazar el registro o la solicitud de acceso a la plataforma a usuarios que tengan antecedentes judiciales, o que, a nuestro criterio, pudieran representar un riesgo para otros usuarios, empresas aliadas o para la misma empresa EXPERTOBRA S.A.S.
        <br>
        •	Responsabilidad de la plataforma. La plataforma no se hace responsable de la selección de los candidatos por parte de las empresas, ni de la calidad o el cumplimiento de las condiciones laborales ofrecidas por las empresas contratantes, pero en caso de que el usuario candidato sienta que está siendo o fue afectado por la empresa contratante, podrá realizar su queja con la empresa EXPERTOBRA S.A.S. quien realizara la investigación del caso y tomara sus medidas correspondientes.
        <br>
        •	Uso de la información. La plataforma puede utilizar la información proporcionada por los usuarios con fines estadísticos, envió de información de servicios que ofrezca la plataforma, siempre protegiendo la privacidad de los usuarios.
        <br>
        •	Propiedad intelectual. Los derechos de propiedad intelectual sobre los contenidos de cada publicación de oferta de empleo ofrecido a través de la plataforma pertenecen a la empresa contratante. La reproducción, distribución o modificación de dichos contenidos sin autorización expresa de la empresa está prohibida.
        <br>
        •	Política de privacidad y protección de datos personales. La empresa se compromete a cumplir con la normativa vigente en materia de protección de datos personales. La empresa recopila y procesa los datos personales del usuario con el fin de prestar los servicios ofrecidos a través de la plataforma. El usuario puede ejercer sus derechos de acceso, rectificación, cancelación y oposición mediante los medios establecidos en la plataforma.
        <br>
        •	Resolución de conflictos. Cualquier conflicto que surja entre el usuario y el tercero prestador del servicio será resuelto mediante los medios establecidos en el acuerdo entre el usuario y el tercero prestador del servicio.
        <br>
        •	Modificación de los términos y condiciones. La empresa se reserva el derecho de modificar estos términos y condiciones en cualquier momento. Los cambios entrarán en vigor a partir del momento de su publicación en la plataforma y serán notificados al usuario registrado en la plataforma. El uso continuado de la plataforma después de la publicación de los cambios implicará la aceptación de los mismos por parte del usuario.
        <br>
        •	Advertencia de seguridad. La plataforma se compromete a enviar un informe a todos los usuarios registrados que, aunque se han implementado medidas de seguridad para proteger la plataforma y los datos de los usuarios, ha sido vulnerada su protección por uno o más posibles ataques cibernéticos. Se informa a los usuarios que los ataques cibernéticos son un riesgo inherente en el uso de Internet y que la plataforma no se hace responsable de los daños causados por estos ataques, pero se compromete en caso de que esto suceda, a tomar las medidas legales y tecnológicas correspondientes para proteger a los usuarios registrados en la plataforma.
        <br><br>
        <b>4.	CURSOS</b><br><br>
        
        •	Servicios. La plataforma EXPERTOBRA ofrece servicios de pago por curso en línea en vivo en diversas áreas de Ingeniería Civil, Arquitectura y Topografía que son: materiales para construcción, seguridad en obra, redes eléctricas, saneamiento, vías y transporte, hidráulica, medio ambiente, construcción, diseño, estructuras, gestión en obra, geotecnia, interventorías, urbanismo y que contaran con diferentes precios cada uno. Los cursos son impartidos por instructores cualificados y experimentados. Nosotros utilizamos el servicio de una plataforma externa para impartir cada curso llamada Microsoft Teams para las sesiones en vivo.
        <br>
        •	Registro y Cuenta de Usuario. Para acceder a nuestros servicios solo debes ingresar a la sección de curso virtual, selección uno o más cursos ofertados de tu interes personal, y realizar la compra del curso donde llegara a tu correo electrónico la confirmación de tu compra, posteriormente te llegara el enlace o link de ingreso único que le permitirá unirse a las clases en vivo que se realizaran en la plataforma Microsoft Teams. Para acceder a esta plataforma deberá crear una cuenta de usuario proporcionando información precisa y completa, aceptando los términos y condiciones si esta le exige. Es su responsabilidad mantener la confidencialidad de su información de inicio de sesión y utilizarla únicamente para acceder a las clases en vivo a través del link recibido por la plataforma WW.EXPERTOBRA.COM. Los usuarios se comprometen a respetar las normas de conducta establecidas por la plataforma EXPERTOBRA S.A.S. y por Microsoft Teams. No se permitirá ningún tipo de conducta inapropiada, como acoso, saboteo o distracción de la clase, discriminación, insultos o difamación.
        <br>
        •	Pago de un Curso. Los usuarios pueden comprar los cursos utilizando PayPal, tarjeta de crédito o débito. La plataforma se reserva el derecho de modificar las opciones de pago en cualquier momento. Al comprar un curso, el usuario acepta pagar el monto y cualquier impuesto o comisión aplicable correspondiente indicado por su método de pago seleccionado en la plataforma. El usuario recibirá un correo electrónico de confirmación de la compra después de completar la transacción. Si el usuario no recibe el correo electrónico de confirmación, debe contactar a la plataforma para verificar la transacción. Cualquier disputa relacionada con la compra de un curso utilizando esta plataforma se resolverá mediante un proceso de mediación o arbitraje, de acuerdo con las leyes aplicables. Si experimenta problemas con el pago, comuníquese con nuestro servicio de atención al cliente lo antes posible para que podamos ayudarlo a resolver el problema.
        <br>
        •	Responsabilidad de los instructores y monitores. Los Instructores y monitores se comprometen a proporcionar información precisa y actualizada en los cursos y a responder a las preguntas de los usuarios de manera oportuna, son responsables de proporcionar un ambiente seguro y respetuoso para todos los usuarios, Los instructores o monitores deben respetar los derechos de propiedad intelectual de terceros y no pueden utilizar material protegido por derechos de autor sin permiso. Los instructores o monitores deben cumplir con todas las leyes y regulaciones aplicables a su enseñanza y a los contenidos de los cursos. Los instructores o monitores no deben hacer ningún tipo de discriminación o acoso en contra de los usuarios. Los instructores o monitores deben tratar a los usuarios de manera justa e imparcial, sin favorecer a ningún usuario en particular. Los instructores o monitores no pueden compartir información personal de los usuarios con terceros, ni utilizar dicha información para fines no relacionados con la enseñanza del curso. Los instructores o monitores se comprometen a proteger los datos personales de los usuarios de acuerdo con las leyes de protección de datos aplicables. Los instructores o monitores no podrán utilizar las clases grabadas o material del curso para intereses económicos propios, compartirlos con terceros o subirlo en alguna plataforma ya que son propiedad intelectual de la empresa EXPERTOBRA S.A.S. 
        <br>
        •	Cambio de fecha para inicio del curso. La plataforma se reserva el derecho de cambiar la fecha de inicio de un curso en línea si no hay suficientes usuarios inscritos para que el curso sea viable. La plataforma siempre notificará a los usuarios inscritos del cambio de fecha de inicio por correo electrónico o por cualquier otro medio de comunicación utilizado para la inscripción. La plataforma se compromete a proporcionar una nueva fecha de inicio que sea lo más conveniente posible para los usuarios inscritos. Los usuarios inscritos pueden optar por recibir un reembolso completo si la nueva fecha de inicio no es adecuada para ellos. Si la plataforma cancela un curso debido a la falta de inscripciones, los usuarios inscritos recibirán un reembolso completo. La plataforma no será responsable de cualquier pérdida o daño que pueda resultar del cambio de fecha de inicio del curso. La plataforma se reserva el derecho de modificar o cancelar un curso en cualquier momento y a su sola discreción. 
        <br>
        •	Cancelación y reembolso. El usuario puede cancelar los servicios solicitados a través de la plataforma en cualquier momento, siempre y cuando se cumplan las condiciones establecidas en el acuerdo entre el usuario y EXPERTOBRA S.AS. Los reembolsos estarán sujetos a las políticas de cancelación y reembolso establecidas por EXPERTOBRA S.A.S.
        <br>
        •	Políticas de cancelación y reembolso. Los usuarios pueden cancelar su inscripción en un curso virtual en cualquier momento antes del inicio del curso. La plataforma proporcionará un reembolso completo si se cancela la inscripción antes del inicio del curso, pero no será responsable de algún tipo de impuesto o comisión impuesto por el método de pago utilizado por el usuario. Si un usuario cancela su inscripción después del inicio del curso, no será elegible para un reembolso. Si la plataforma cancela un curso debido a circunstancias imprevistas, como problemas técnicos o la falta de un instructor, se proporcionará un reembolso completo a los usuarios inscritos. Si la plataforma cancela un curso debido a la falta de inscripciones, se proporcionará un reembolso completo a los usuarios inscritos. Los usuarios que deseen cancelar su inscripción deben hacerlo a través del servicio al cliente de la plataforma o por correo electrónico y proporcionar su información de pago para recibir el reembolso. El tiempo de procesamiento del reembolso dependerá del método de pago utilizado y puede tardar hasta 10 días hábiles. La plataforma no será responsable de ninguna pérdida o daño que pueda resultar de la cancelación de la inscripción en un curso en línea.
        <br>
        •	Veracidad de la información de usuarios. Al registrarse en la plataforma para inscribirse en un curso en línea, los usuarios deben proporcionar información precisa y veraz sobre sí mismos. La plataforma no se hace responsable de la veracidad o exactitud de esta información.
        <br>
        •	Publicación de cursos. Los instructores interesados en publicar un curso en la plataforma deben completar el proceso de solicitud de publicación proporcionando información detallada sobre el curso, incluidos los materiales del curso, los objetivos de aprendizaje y el tiempo de duración. La plataforma se reserva el derecho de aprobar o rechazar cualquier solicitud de publicación de curso a su sola discreción. Los instructores que publiquen un curso en la plataforma deben garantizar que todo el contenido del curso sea legal y respete los derechos de autor y otros derechos de propiedad intelectual. Los instructores entregan todos los derechos de propiedad intelectual sobre su contenido de curso, a la plataforma y empresa EXPERTOBRA S.A.S. para utilizar, mostrar y comercializar el contenido del curso en la plataforma y cada clase en vivo grabada. La plataforma se reserva el derecho de modificar o retirar cualquier curso publicado en la plataforma si se determina que el contenido del curso es inapropiado o viola los términos y condiciones de la plataforma. Los instructores son responsables de proporcionar información precisa y actualizada sobre el curso y actualizar el contenido del curso según sea necesario. Los instructores aceptan cumplir con todas las leyes y regulaciones aplicables en relación con el contenido del curso y su publicación en la plataforma. 
        <br>
        •	Contrato del Instructor. La plataforma y el instructor acuerdan los términos y condiciones para la prestación de servicios de enseñanza en línea, incluyendo los horarios, la duración y el alcance de los cursos. El instructor se compromete a proporcionar servicios de enseñanza en línea de alta calidad y a cumplir con los objetivos de aprendizaje del curso. La plataforma se compromete a proporcionar las herramientas y la tecnología necesarias para llevar a cabo los cursos en línea. La plataforma y el instructor acuerdan los términos financieros, incluidos los pagos por los servicios de enseñanza en línea, El instructor entrega todos los derechos de propiedad intelectual a la plataforma y empresa EXPERTOBRA S.A.S. sobre el contenido y clases grabadas del curso, La plataforma se reserva el derecho de modificar o retirar cualquier curso publicado en la plataforma si se determina que el contenido del curso es inapropiado o viola los términos y condiciones de la plataforma. El instructor se compromete a proporcionar información precisa y actualizada sobre el curso y actualizar el contenido del curso según sea necesario. El instructor acepta cumplir con todas las leyes y regulaciones aplicables en relación con la prestación de servicios de enseñanza en línea en la plataforma. La plataforma se reserva el derecho de rescindir el contrato en cualquier momento si el instructor no cumple con los términos y condiciones establecidos en el contrato. El instructor acepta estos términos y condiciones al aceptar el contrato de prestación de servicios para dictar el curso en la plataforma.
        
        <br>
        •	Cancelación del registro. La plataforma se reserva el derecho de cancelar una transacción en caso de detectar que se ha utilizado información de pago falsa o robada.
        <br>
        •	Cancelación de una clase en vivo. En caso de que los instructores o monitores deban cancelar una clase en vivo, se comprometen a comunicarlo a los usuarios con la debida antelación por todos los medios comunicativos suministrados por el usuario. Los usuarios no se verán afectados por esta cancelación y volverán a recibir esta clase en una fecha posterior que se las dará el instructor a cargo. 
        <br>
        •	Confidencialidad. Toda la información proporcionada por los usuarios en el contexto de las pruebas realizadas durante el curso inscrito, se mantendrá en estricta confidencialidad por parte del instructor o monitor. Esta información solo se utilizará para llevar a cabo un promedio de notas de cada usuario inscrito, para posteriormente ser recompensado por la empresa EXPERTOBRA S.A.S. con su programa de becas de educación.
        <br>
        •	Responsabilidades de la Empresa. La plataforma se compromete a garantizar que todos los cursos ofrecidos en la plataforma sean precisos, actualizados y relevantes para los usuarios interesados. La plataforma hará todo lo posible para garantizar que el contenido del curso sea de alta calidad y cumpla con las expectativas de los usuarios interesados. Además, la plataforma realizara un exigente proceso de selección para asegurarse de que los instructores estén calificados y tengan la experiencia necesaria para dictar los cursos. En caso de que se produzca un problema técnico, el usuario debe comunicarse con la plataforma para buscar una solución. La plataforma no es responsable de la conducta de los instructores o monitores, pero se reserva el derecho de cancelar el contrato de un instructor o monitor si se detecta que ha violado cualquiera de los términos y condiciones establecidos en este documento. La plataforma se reserva el derecho de cancelar una transacción en caso de detectar que se ha utilizado información de pago falsa o robada. La plataforma se compromete a garantizar que todos los pagos se procesen de manera segura y confidencial. Además de tomar medidas de seguridad para proteger los datos financieros de los usuarios, La plataforma no se hace responsable de problemas técnicos en la plataforma de pago, incluyendo errores de procesamiento de pagos o fallas en la transacción. La plataforma se compromete a garantizar que los pagos se realicen de manera oportuna y que se proporcionen recibos o comprobantes de pago a los usuarios.
        <br>
        •	Uso de la información. La plataforma puede utilizar la información proporcionada por los usuarios con fines estadísticos, envió de información de servicios que ofrezca la plataforma, siempre protegiendo la privacidad de los usuarios.
        <br>
        •	Propiedad intelectual. Los derechos de propiedad intelectual sobre los contenidos de cada curso ofrecido a través de la plataforma y las clases que serán grabadas en la plataforma Microsoft Teams pertenecen a la empresa EXPERTOBRA S.A.S. BIC. La reproducción, distribución o modificación de dichos contenidos sin autorización expresa de la empresa está prohibida.
        <br>
        •	Política de privacidad y protección de datos personales. La empresa se compromete a cumplir con la normativa vigente en materia de protección de datos personales. La empresa recopila y procesa los datos personales del usuario con el fin de prestar los servicios ofrecidos a través de la plataforma. El usuario puede ejercer sus derechos de acceso, rectificación, cancelación y oposición mediante los medios establecidos en la plataforma.
        <br>
        •	Resolución de conflictos. Cualquier conflicto que surja entre el usuario y el tercero prestador del servicio será resuelto mediante los medios establecidos en el acuerdo entre el usuario y el tercero prestador del servicio.
        <br>
        •	Modificación de los términos y condiciones. La empresa se reserva el derecho de modificar estos términos y condiciones en cualquier momento. Los cambios entrarán en vigor a partir del momento de su publicación en la plataforma y serán notificados al usuario registrado en la plataforma. El uso continuado de la plataforma después de la publicación de los cambios implicará la aceptación de los mismos por parte del usuario.
        <br>
        •	Advertencia de seguridad. La plataforma se compromete a enviar un informe a todos los usuarios registrados que, aunque se han implementado medidas de seguridad para proteger la plataforma y los datos de los usuarios, ha sido vulnerada su protección por uno o más posibles ataques cibernéticos. Se informa a los usuarios que los ataques cibernéticos son un riesgo inherente en el uso de Internet y que la plataforma no se hace responsable de los daños causados por estos ataques, pero se compromete en caso de que esto suceda, a tomar las medidas legales y tecnológicas correspondientes para proteger a los usuarios registrados en la plataforma.
        <br><br>
        <b>5.	CURSOS PRESENCIALES</b><br><br>
        
        •	Servicios. Nuestra plataforma a través de alianzas estratégicas ofrece cursos presenciales en diversas áreas de Ingeniería Civil, Arquitectura y Topografía que son: materiales para construcción, seguridad en obra, redes eléctricas, saneamiento, vías y transporte, hidráulica, medio ambiente, construcción, diseño, estructuras, gestión en obra, geotecnia, interventorías, urbanismo, ofrecidos por empresas, o Universidades, que contaran con diferentes precios. 
        <br>
        •	Registro y Cuenta de Usuario. Para acceder a cursos presenciales solo debes ingresar a la sección de curso virtual, seleccionar uno o más cursos ofertados de tu interes personal, y realizar la compra del curso, donde llegará a tu correo electrónico la confirmación de tu compra, posteriormente te llegará la información de ingreso único que le permitirá unirse a las clases del proveedor externo encargado de impartir este curso de manera presencial. Para acceder a esta plataforma deberá crear una cuenta de usuario proporcionando información precisa y completa, aceptando los términos y condiciones que esta le exige. Es su responsabilidad mantener la confidencialidad de su información de inicio de sesión y utilizarla únicamente para acceder a las clases presenciales en las sedes de estas empresas o Universidades aliadas. El usuario reconoce y acepta que, al registrarse en un curso dictado por un proveedor externo, está sujeto a los términos y condiciones establecidos por dicho proveedor externo.
        <br>
        •	Pago de un Curso. Los usuarios pueden comprar los cursos utilizando PayPal, tarjeta de crédito o débito. La plataforma se reserva el derecho de modificar las opciones de pago en cualquier momento. Al comprar un curso, el usuario acepta pagar el monto y cualquier impuesto o comisión aplicable correspondiente indicado por su método de pago seleccionado en la plataforma. El usuario recibirá un correo electrónico de confirmación de la compra después de completar la transacción. Si el usuario no recibe el correo electrónico de confirmación, debe contactar a la plataforma para verificar la transacción. Cualquier disputa relacionada con la compra de un curso utilizando esta plataforma se resolverá mediante un proceso de mediación o arbitraje, de acuerdo con las leyes aplicables. Si experimenta problemas con el pago, comuníquese con nuestro servicio de atención al cliente lo antes posible para que podamos ayudarlo a resolver el problema. Los cursos ofrecidos por proveedores externos son responsabilidad exclusiva de dichos proveedores y no representan necesariamente los puntos de vista o las políticas de la plataforma EXPERTOBRA S.A.S.
        <br>
        •	Responsabilidad de Proveedor Externo. Los proveedores externos aceptan que son responsables de la calidad y el contenido de los cursos que ofrecen en la plataforma. Los proveedores externos aceptan indemnizar y eximir de responsabilidad a la plataforma y a sus afiliados, directivos, empleados y agentes en caso de que surjan reclamos, acciones legales, demandas, daños y perjuicios, costos y gastos relacionados con los cursos que ofrecen en la plataforma. Los proveedores externos aceptan cumplir con todas las leyes, reglamentaciones y normas aplicables en relación con los cursos que ofrecen en la plataforma. Los proveedores externos aceptan que la plataforma no será responsable por ningún daño o perjuicio derivado de su incumplimiento de los términos y condiciones establecidos para los proveedores externos. Los proveedores externos aceptan que la plataforma se reserva el derecho de eliminar cualquier curso que no cumpla con sus estándares de calidad o que incumpla con los términos y condiciones establecidos.
        <br>
        •	Cambio de fecha para inicio del curso. Si el proveedor externo necesita cambiar las fechas del curso por razones imprevistas, el proveedor externo se esforzará por informar a la plataforma y empresa EXPERTOBRA S.A.S. y a los usuarios lo antes posible en caso de cambios en las fechas del curso. Si se produce un cambio de fecha del curso, el proveedor externo y la plataforma se esforzarán por ofrecer a los usuarios una nueva fecha que sea conveniente para la mayoría de los usuarios. Si los usuarios no pueden asistir a la nueva fecha del curso, el proveedor externo y la plataforma se esforzarán por ofrecer una alternativa, como un reembolso completo o un crédito para otro curso. El proveedor externo acepta que es responsable de informar a los usuarios de cualquier cambio de fecha del curso lo antes posible y de responder a cualquier pregunta o inquietud que los usuarios puedan tener sobre el cambio. El proveedor externo acepta que la plataforma no será responsable de ningún daño o perjuicio derivado de un cambio de fecha del curso.
        <br>
        •	Cancelación y reembolso. Los usuarios deben informar al proveedor externo de cualquier cancelación lo antes posible. Si el usuario cancela su inscripción en el curso dentro del período establecido por la política de cancelación y reembolso del proveedor externo, se le ofrecerá un reembolso según los términos de dicha política. El proveedor externo acepta que la plataforma no será responsable de ningún daño o perjuicio derivado de la cancelación del curso.
        <br>
        •	Políticas de cancelación y reembolso. Si el usuario no cumple con el plazo de cancelación establecido por la política de cancelación y reembolso del proveedor externo, no se le ofrecerá un reembolso. Si el usuario no asiste al curso sin notificar al proveedor externo de su ausencia, no se le ofrecerá un reembolso. Si el proveedor externo necesita cancelar un curso, se esforzará por informar a los usuarios lo antes posible y ofrecerá un reembolso completo. Si el proveedor externo no puede proporcionar el curso tal como se describe, se ofrecerá a los usuarios un reembolso completo. Si el proveedor externo cancela el curso debido a una situación que está bajo su control, se aplicará la política de cancelación y reembolso del proveedor externo.
        <br>
        •	Veracidad de la información de usuarios. Todos los usuarios y proveedores externos deben proporcionar información precisa y veraz al registrarse en la plataforma y al crear sus perfiles. Los usuarios y proveedores externos son los únicos responsables de la veracidad de la información que proporcionan a la plataforma, y cualquier información falsa o engañosa puede resultar en la eliminación del perfil o en la terminación de la relación comercial. La plataforma se reserva el derecho de verificar la información proporcionada por los usuarios y proveedores externos, y puede solicitar pruebas adicionales si sospecha que la información proporcionada no es precisa o veraz. La plataforma no se hace responsable de la información proporcionada por los usuarios y proveedores externos, y no garantiza la veracidad de dicha información. Si un usuario o proveedor externo proporciona información falsa o engañosa que resulta en daños a otro usuario o a la plataforma, será responsable de dichos daños y deberá indemnizar a las partes afectadas. La plataforma se reserva el derecho de suspender o cancelar la cuenta de cualquier usuario o proveedor externo que proporcione información falsa o engañosa.
        <br>
        •	Publicación de cursos. El proveedor externo debe completar el proceso de registro y presentar toda la información necesaria para la publicación del curso. La plataforma se reserva el derecho de aceptar o rechazar la publicación del curso en función de la calidad del contenido, la idoneidad del tema y el cumplimiento de los términos y condiciones. El proveedor externo debe proporcionar una descripción clara y precisa del contenido del curso, su duración, los requisitos previos, los objetivos de aprendizaje y los materiales que se proporcionarán. El proveedor externo es el único responsable de la calidad del contenido, la exactitud de la información y la legalidad del curso que ofrece. El proveedor externo debe proporcionar el contenido del curso en el formato especificado y garantizar que el contenido sea original y no infrinja los derechos de propiedad intelectual de terceros. El proveedor externo debe proporcionar un calendario de fechas y horarios para el curso y cumplir con los mismos. El proveedor externo debe responder a las preguntas y consultas de los usuarios de manera oportuna y profesional. La plataforma se reserva el derecho de retirar un curso en cualquier momento, sin previo aviso, si se determina que el contenido es inapropiado o infringe los términos y condiciones. Los usuarios que se inscriben en el curso del proveedor externo están sujetos a los términos y condiciones del proveedor externo en relación con los pagos, cancelaciones, reembolsos y otros asuntos relacionados con el curso. El proveedor externo acepta que la plataforma puede retener una comisión por cada estudiante inscrito en el curso según lo acordado en el contrato.
        <br>
        •	Contrato del Proveedor externo. El proveedor externo confirma que tiene los derechos de propiedad intelectual necesarios para ofrecer los cursos en la plataforma y que cualquier material o contenido proporcionado no viola los derechos de propiedad intelectual de terceros. El proveedor externo es responsable de garantizar la calidad y el contenido de los cursos que se ofrecen en la plataforma. Además, el proveedor externo es responsable de garantizar que cumple con todas las leyes y regulaciones aplicables en la prestación de los servicios. El proveedor externo se compromete a pagar a la plataforma una comisión acordada por cada usuario que se inscriba en los cursos ofrecidos por la plataforma y empresa EXPERTOBRA S.A.S. Los pagos se realizarán de acuerdo con los términos y condiciones acordados por ambas partes. El proveedor externo acuerda cumplir con la política de cancelación y reembolso establecida en los términos y condiciones de la plataforma. Además, el proveedor externo acuerda reembolsar cualquier pago recibido en caso de que un curso deba cancelarse. Ambas partes acuerdan mantener la confidencialidad de la información del otro y utilizar dicha información únicamente para los fines del contrato. Cualquiera de las partes puede rescindir el contrato en cualquier momento mediante notificación por escrito si la otra parte incumple los términos y condiciones establecidos en el contrato. Cualquier disputa que surja en relación con este contrato se resolverá mediante arbitraje de acuerdo con las reglas de arbitraje de las autoridades colombianas, país en el que está establecida la plataforma.
        <br>
        •	Cancelación del registro. Si un usuario desea cancelar su registro en un curso dictado por un proveedor externo, debe seguir las políticas de cancelación y reembolso establecidas por el proveedor externo. La plataforma se reserva el derecho de cancelar el registro de un proveedor externo en cualquier momento si se determina que está violando los términos y condiciones establecidos.
        <br>
        •	Confidencialidad. La plataforma se compromete a proteger la confidencialidad de la información personal de los usuarios y proveedores externos, y a cumplir con las leyes de protección de datos aplicables. Los usuarios y proveedores externos aceptan no compartir información confidencial de la plataforma con terceros sin el consentimiento explícito de la plataforma. La plataforma se compromete a proteger la confidencialidad de la información relacionada con los cursos publicados por proveedores externos, incluyendo los materiales del curso y los datos de los estudiantes.
        <br>
        •	Uso de la información. La plataforma puede utilizar la información proporcionada por los usuarios con fines estadísticos, envió de información de servicios que ofrezca la plataforma, siempre protegiendo la privacidad de los usuarios.
        <br>
        •	Propiedad intelectual. Los derechos de propiedad intelectual sobre los contenidos de cada curso ofrecido de manera presencial pertenecen a la empresa encargar de enseñar ese curso. La reproducción, distribución o modificación de dichos contenidos sin autorización expresa de la empresa está prohibida.
        <br>
        •	Política de privacidad y protección de datos personales. La empresa se compromete a cumplir con la normativa vigente en materia de protección de datos personales. La empresa recopila y procesa los datos personales del usuario con el fin de prestar los servicios ofrecidos a través de la plataforma. El usuario puede ejercer sus derechos de acceso, rectificación, cancelación y oposición mediante los medios establecidos en la plataforma.
        <br>
        •	Resolución de conflictos. Cualquier conflicto que surja entre el usuario y el tercero prestador del servicio será resuelto mediante los medios establecidos en el acuerdo entre el usuario y el tercero prestador del servicio.
        <br>
        •	Modificación de los términos y condiciones. La empresa se reserva el derecho de modificar estos términos y condiciones en cualquier momento. Los cambios entrarán en vigor a partir del momento de su publicación en la plataforma y serán notificados al usuario registrado en la plataforma. El uso continuado de la plataforma después de la publicación de los cambios implicará la aceptación de los mismos por parte del usuario.
        <br>
        •	Advertencia de seguridad. La plataforma se compromete a enviar un informe a todos los usuarios registrados que, aunque se han implementado medidas de seguridad para proteger la plataforma y los datos de los usuarios, ha sido vulnerada su protección por uno o más posibles ataques cibernéticos. Se informa a los usuarios que los ataques cibernéticos son un riesgo inherente en el uso de Internet y que la plataforma no se hace responsable de los daños causados por estos ataques, pero se compromete en caso de que esto suceda, a tomar las medidas legales y tecnológicas correspondientes para proteger a los usuarios registrados en la plataforma.
        
        </p>
        <form method="post">
        <p align="center"><input type="submit" class="btn btn-danger btn-lg" value="Cerrar" name="cerrar"></p>
        </form>
</table>
</body>
</html>